export { default as frame1 } from "./Frame1.png";
export { default as LogoSvg } from "./Logo.svg";
export { default as team_member1 } from "./avatar1.png";
export { default as team_member2 } from "./avatar2.png";
export { default as team_member3 } from "./avatar3.png";
export { default as aws } from "./aws-svgrepo-com 1.svg";
export { default as figma } from "./figma-5 1.svg";
export { default as footer_left_bubble } from "./footer_left_bubble.png";
export { default as footer_right_bubble } from "./footer_right_bubble.png";
export { default as grow_features_img } from "./grow_im.png";
export { default as lanuch_features_img } from "./lanuch_fea_img.png";
export { default as left_boble } from "./left_bubble.png";
export { default as location } from "./location.png";
export { default as mix_panel } from "./mixpanel 1.svg";
export { default as news2 } from "./news1.png";
export { default as news1 } from "./news2.png";
export { default as news3 } from "./news3.png";
export { default as nes_bulb_l } from "./news_bulb.png";
export { default as nextjs } from "./next-js 1.svg";
export { default as openAi } from "./openai-2 1.svg";
export { default as react_logo } from "./reactjs.svg";
export { default as re_tools } from "./retool-logos-idpLYn9I4G 1.svg";
export { default as right_boble } from "./right_bubble.png";
export { default as svelte } from "./svelte-1 1.svg";
export { default as uber } from "./uber.svg";
export { default as validate_feature_img } from "./validate.png";
export { default as w_logo } from "./w.svg";

export { default as airwallex } from "./airwallex.svg";
export { default as asana } from "./asant.svg";
export { default as asets2 } from "./assets2.png";
export { default as fresh_work } from "./fresh work.svg";
export { default as g6 } from "./g10.png";
export { default as github } from "./github.svg";
export { default as out_race } from "./outrace.svg";

